### ISSUE TITLE
Codepage

### ISSUE THREAD

**Issue by kobzar** [magopian/django-data-exports#6]
Thanks for you job!
This is wonderful and usable app.
But, do you can add codepages on Export settings? Example some of my users work on windows, another mac, linux, e.t.c.
And windows users can't read utf-8 usually method.
Thanks again!

**Comment by magopian** [comment]
Hi,

I'm not sure I understand what you mean, I don't have a windows box, so I can't even test, but from what I understand, Excel is able to read utf-8 content.

**Comment by Christophe31** [comment]
Default excel csv import is not in UTF8. I suppose it depends which is your MS Office localisation. I don't have it right know. http://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0 will probably work. Event if 'open with' is not enough.

**Comment by magopian** [comment]
Thanks @Christophe31 for the link!

I can't quite remember, but I believe I used a trick in the past that was something about rendering an HTML table, and setting the encoding in the `<head>` of the HTML document. You would then save this html document (named with a .cvs extension), and Excel would be tricked in believing it is a CSV document, but use the enconding.
Can't find a link explaining this trick, and can't remember the details sadly.

Otherwise, I could try adding a BOM to the https://github.com/magopian/django-data-exports/tree/master/data_exports/templates/data_exports template, according to this SO answer: http://stackoverflow.com/a/155176

Thoughts?

**Comment by Christophe31** [comment]
yeah, sounds good, I should test, I'll ask to an excel user this week.

**Comment by magopian** [comment]
Hi @Christophe31, should I close this issue? Is it still relevant?

**Comment by Christophe31** [comment]
I don't remember having good result when I tryed. As I don't remember I should try again.

**Comment by magopian** [comment]
Closing this old one now, if you need, please reopen it.
